### ISSUE TITLE
Additional functionality SimulationTimeSeriesMatrix module

### ISSUE THREAD

**Issue by jorgenherje** [equinor/webviz#380]
This is a list of additional functionality for the SimulationTimeSeriesMatrix module. 

The module is a conversion of the ["Simulation time series"-plugin](https://webviz-subsurface-example.azurewebsites.net/simulation-time-series) from `webviz-subsurface`. 

This issue lists functionality in the categories:
- `Remaining functionality from plugin`: Remaining functionality not converted into the new module. 
- `Adjustments`: Adjustment of existing functionality in the module
- `New functionality`: New/additional functionality to include into the module

These are all suggestions and up for discussion. Feel free to request additional functionality or to remove unwanted listed functionalities. 

---

#### Remaining functionality from plugin: 
- [ ] Realization filter/selection - awaits https://github.com/equinor/webviz/issues/348
- [ ] "Data relative to date" selection
- [ ] `VectorCalculator` - awaits https://github.com/equinor/webviz/issues/379
- [ ] `Delta Ensembles` - awaits https://github.com/equinor/webviz/issues/215
- [ ] `PER_DAY` and `PER_INTVL` vectors
- [ ] Custom vector definitions?
- [ ] Observations

#### Adjustments:
- [ ] `m*n` grid layout for plot
- [ ] Styling of subplots, e.g. titles etc.?

#### New functionality:
- [ ] Parameter filtering - awaits https://github.com/equinor/webviz/issues/321
- [ ]  ....
