### ISSUE TITLE
Persistence of dashboard

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz#544]
Sparring partner: @sigurdp 

---

1st iteration
- Implement front-end mechanism

2nd iteration
- Research database solution
- Start database service
- Implement backend service

Dependency of #545, #578

---

From before:

### Details
- Storing dashboard states on server (auto-save)
- Support for working with multiple dashboards simultaneously
- Creating new dashboards/cloning shared ones

See also #537 

---
### Open questions

- [ ] What data is going to be stored and how? Module states, GUI states, user created items
- [ ] How are we handling permission of user-created items?
- [ ] Are user-created items related to a field or to a dashboard?
Data in DB is stored with used fields as metadata (owner, field)
Checkbox when creating link for making accessible for partners
Shared dashboard state is immutable but links can be deleted or partner access can be changed, make access to shared dashboards valid in a chosen period
When links are created the author can add a description - when shared dashboard is opened, an info box is displayed.
- [ ] When sharing a dashboard, are user-created items used in there automatically shared?
- [ ] Does the backend have to have a relation to the persisted data? Where does the business logic division start?
- [ ] Is there other data we want to store?
- [ ] How do we handle when users are sharing a dashboard showing a field another user does not have access to?
Display information that user does not have access to one or more fields used in the shared dashboard - show additional info on how to solve.
- [ ] What about versioning?

Wait with sharing of user-created items without links.
User must actively save states of a dashboard, otherwise it's always the latest state.
