### ISSUE TITLE
Coviz prototype implementation (3D grid)

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz#608]
- [x] Create mechanism for storing/accessing custom user data (as e.g. custom polylines, vector calculator expressions, selected color palette for parameter) from workbench session
- [x] Back-sampling of intersection data to actual wellbore path
- [x] More feature-rich SubsurfaceViewer wrapper (drawing polylines, keep camera position etc.)
- [x] Make example of large failing grid for Aspentech to reproduce (Snorre, grid layer = -1)
- [x] Workbench hover mechanism for wellbores/custom polylines
- [ ] Workbench select mechanism for wellbores/custom polylines etc...
- [ ] Different modules
    - [ ] Grid3D as data provider model (ensemble ident, realization, intersection, grid model/parameter/date...)
    - [ ] EsvIntersection module as potential data receiver
        - Has basic implementation for visualizing data from Grid3D
        - Has different optional additional modes for structural uncertainty and seismic
        - Can be used as independent or as submodule to Grid3D (data channels)

**Comment by rubenthoms** [comment]
All remaining tasks summarized in #767.
