### ISSUE TITLE
Suggestions for functionality that migth be implemented in Webviz

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz#720]
I have gathered a list of typical visualisations and analysis functionality that people in the FMU community might have to implement in another tool than Webviz. Maybe some of this can be implemented in Webviz in some way at some point:

- [ ] #784
- [x] General scatter plotting functionality. Between summary data and parameters, but also other output like f.ex the volumetrics tables.
- [ ] Plotting other time series than summary vectors in the TimeSeries visualisation. It can be f.ex ecalc-output or other time series you want to calculate yourself, but is to advanced for the vector calculator. In the old webviz it is possible to open the summary arrow file and add columns.
- [ ] Visualisation of discrete vectors in the TimeSeries plotter (f.ex WMCTL). Statistics makes no sense, but f.eks an area plot can be useful (like in the `WellAnalysis` plugin in the `webviz-subsurface`).
- [ ] #786
- [ ] Recovery factor/production per region and zone (and facies/source/ensemble). Kind of like the functionality in `VolumetricAnalysis`, but for dynamic data.
- [ ] Production/injection per well and being able to compare ensembles (Something like `WellAnalysis` in `webviz-subsurface`).

**Comment by anders-kiaer** [comment]
> Analysis of ERT AHM output. The most basic is to have access to all observations, simulated responses/misfit and parameters that ERT actually uses in the assisted history matching. And then be able to cross plot and analyse correlations. Vi have some of the functionality in ParameterAnalysis and RftPlotter in the webviz-subsurface.

Open question if we should do the `(response - observation)` diff by ourselves, or get it from ERT.
We want to get upscaling of error from ERT.

> General scatter plotting functionality. Between summary data and parameters, but also other output like f.ex the volumetrics tables.

Might be possible with data channels.

> Plotting other time series than summary vectors in the TimeSeries visualisation. It can be f.ex ecalc-output or other time series you want to calculate yourself, but is to advanced for the vector calculator. In the old webviz it is possible to open the summary arrow file and add columns.

Need to ask `fmu-dataio` to add CCS data and eCalc time series.

**Comment by lindjoha** [comment]
For the point about general scatter plotting functionality I want to add the possibility to scatter plot the delta between two ensembles, and the delta between two time steps, vs f.ex parameters.
