### ISSUE TITLE
`fmu-dataio` data requests

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz#736]
This is not a webviz issue per se, but a placeholder/container for data requests communicated to `fmu-dataio` project:

- [ ] Abstract away things: https://github.com/equinor/fmu-dataio/issues/668 (will make it easier for user to start using webviz modules, and easier maintenance on fmu-dataio side).
- [ ] Parent grid: https://github.com/equinor/fmu-dataio/issues/278
- [ ] Blocked/modelled well logs: https://github.com/equinor/fmu-dataio/issues/372
- [ ] FIPNUM vs region/zone mapping: https://github.com/equinor/fmu-dataio/issues/532
- [ ] Observations
- [ ] Well uuid / alias mapping
- [ ] Richer ensemble metadata https://github.com/equinor/fmu-dataio/issues/299

**Comment by anders-kiaer** [comment]
**Actions from meeting Sep 23rd:**
- [ ] SUMO make `data.geometry` metadata searchable (introduced in https://github.com/equinor/fmu-dataio/pull/677).
